/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pertemuan11;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.awt.Frame;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import pertemuan11.Datasiswa;

/**
 *
 * @author LENOVO
 */

public class Update extends javax.swing.JDialog {

  
    String namaLama, absenLama, walkelLama, walmurLama;

    /**
     * Creates new form Update
     */
    public Update(java.awt.Frame parent, boolean modal, String namaLama, String absenLama, String walkelLama, String walmurLama) {
        super(parent, modal);
        initComponents();

        this.namaLama = namaLama;
        this.absenLama = absenLama;
        this.walkelLama = walkelLama;
        this.walmurLama = walmurLama;

        txtNama.setText(namaLama);
        txtAbsen.setText(absenLama);
        txtWalkel.setText(walkelLama);
        txtWalmur.setText(walmurLama);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtAbsen = new javax.swing.JTextField();
        txtWalkel = new javax.swing.JTextField();
        txtWalmur = new javax.swing.JTextField();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("NAMA");

        jLabel2.setText("ABSEN");

        jLabel3.setText("WALI KELAS");

        jLabel4.setText("WALI MURID");

        txtAbsen.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(30, 321, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtAbsen)
                            .addComponent(txtWalkel)
                            .addComponent(txtWalmur))
                        .addGap(0, 137, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtWalkel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtWalmur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtNama.getText().isEmpty()
                || txtAbsen.getText().isEmpty()
                || txtWalkel.getText().isEmpty()
                || txtWalmur.getText().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Isi Semua Data!");
            return;
        }

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("pertemuan11PU");
        EntityManager em = emf.createEntityManager();

        try {
            em.getTransaction().begin();

            // Cari data berdasarkan absen lama (PK lama)
            int oldAbsen = Integer.parseInt(absenLama);
            Datasiswa m = em.find(Datasiswa.class, oldAbsen);

            if (m == null) {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan!");
                em.getTransaction().rollback();
                return;
            }

            // Ambil nilai baru dari textfield
            int newAbsen = Integer.parseInt(txtAbsen.getText());

            m.setNama(txtNama.getText());
            m.setAbsen(newAbsen); // <- PK boleh diubah
            m.setWaliKelas(txtWalkel.getText());
            m.setWaliMurid(txtWalmur.getText());

            em.merge(m);
            em.getTransaction().commit();

            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");

            // Update nilai PK lama supaya update berikutnya bisa lagi
            absenLama = String.valueOf(newAbsen);

            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        } finally {
            em.close();
            emf.close();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField txtAbsen;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtWalkel;
    private javax.swing.JTextField txtWalmur;
    // End of variables declaration//GEN-END:variables
}
